development:
  adapter: postgresql
  database: shelter_resources_development
test:
  adapter: postgresql
  database: shelter_resources_test
production:
  adapter: postgresql
  database: shelter_resources_production
